# Generated by Django 2.2.24 on 2023-05-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='Покемон', max_length=200)),
                ('title_en', models.CharField(default='Pokemon', max_length=200)),
                ('title_jp', models.CharField(default='ポケモン', max_length=200)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/pokemons')),
                ('img_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Lat.')),
                ('lon', models.FloatField(verbose_name='Lon.')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Appeared at')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Disappeared at')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Level')),
                ('helth', models.IntegerField(blank=True, null=True, verbose_name='Health')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Strength')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='Defence')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='Stamina')),
                ('next_evolutions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolutions', to='pokemon_entities.Pokemon')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon')),
                ('previous_evolutions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_evolutions', to='pokemon_entities.Pokemon')),
            ],
        ),
    ]
