# Generated by Django 2.2.24 on 2023-05-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название покемона (рус.)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название покемона (анг.)')),
                ('title_jp', models.CharField(max_length=200, verbose_name='Название покемона (яп.)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='pokemons', verbose_name='Изображение')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_evolutions', to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционировал')),
            ],
            options={
                'verbose_name_plural': 'Типы покемонов',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='Создан')),
                ('disappeared_at', models.DateTimeField(verbose_name='Исчезает')),
                ('level', models.IntegerField(blank=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, verbose_name='Сила')),
                ('defence', models.IntegerField(blank=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon', verbose_name='Покемон')),
            ],
            options={
                'verbose_name_plural': 'Покемоны на карте',
                'ordering': ['pokemon'],
            },
        ),
    ]
