# Generated by Django 2.2.24 on 2023-05-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20230503_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='next_evolutions',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='previous_evolutions',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolutions', to='pokemon_entities.Pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_evolutions', to='pokemon_entities.Pokemon'),
        ),
    ]
