# Generated by Django 2.2.24 on 2023-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Lat.'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Lon.'),
        ),
    ]
