# Generated by Django 2.2.24 on 2023-05-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20230503_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='next_evolutions',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='previous_evolutions',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.Pokemon', verbose_name='В кого эволюционирует'),
        ),
    ]
