# Generated by Django 2.2.24 on 2023-05-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20230503_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, default='существо Вселенной Покемон Гоу', null=True, verbose_name='Описание'),
        ),
    ]
