# Generated by Django 2.2.24 on 2023-04-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20230427_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='longitude',
            new_name='lon',
        ),
    ]
